[package]
name = "sd-events"
version = "0.1.0"
edition = "2021"

[dependencies]
sd-types = { path = "../sd-types" }
tokio = { version = "1", features = ["sync", "macros"] }
serde = { version = "1", features = ["derive"] }
log = "0.4"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
serde_json = "1"
tokio = { version = "1", features = ["sync", "macros", "rt", "time"] }
