import { defineConfig } from 'vite'
import preact from '@preact/preset-vite'

export default defineConfig({
  plugins: [preact()],
  build: {
    rollupOptions: {
      output: {
        // Content-hashed, which is rollup's default and was overridden here to
        // fixed names. Fixed names mean the browser caches `index.css` and
        // `index.js` independently and can serve a *stale* stylesheet against
        // fresh markup — new elements then render with user-agent defaults,
        // which looks exactly like broken CSS. index.html is generated by vite
        // and references whatever these produce, so nothing needs the names to
        // be stable.
        entryFileNames: 'assets/[name].[hash].js',
        chunkFileNames: 'assets/[name].[hash].js',
        assetFileNames: 'assets/[name].[hash].[ext]',
      },
    },
  },
  server: {
    port: 5173,
    // Must match the port in data/config.json (the repo default). The backend
    // binds an ephemeral port when that config file is removed, which breaks
    // this proxy — keep the file in place for frontend development.
    proxy: {
      '/api': 'http://localhost:3000',
      '/ws': {
        target: 'ws://localhost:3000',
        ws: true,
      },
    },
  },
})
